# Generated by Django 2.1 on 2018-08-31 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='programa',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='asesores',
            field=models.ManyToManyField(to='GestionProyectos.Asesor'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='integrantes',
            field=models.ManyToManyField(to='GestionProyectos.Estudiante'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProyectos.Persona'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProyectos.Programa'),
        ),
    ]
