# Generated by Django 2.1 on 2018-08-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProyectos', '0002_auto_20180831_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Inicio'),
        ),
    ]
